// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Domus;

#nullable disable

namespace DomusDatabase.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220906065845_Initial Creation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("domus.RealEstate", b =>
                {
                    b.Property<int>("finnkodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("finnkodeId"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<float>("lat")
                        .HasColumnType("real");

                    b.Property<float>("lon")
                        .HasColumnType("real");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("sqm")
                        .HasColumnType("integer");

                    b.Property<float>("sqmPrice")
                        .HasColumnType("real");

                    b.HasKey("finnkodeId");

                    b.ToTable("RealEstates");
                });
#pragma warning restore 612, 618
        }
    }
}
